language: node_js
node_js:
  - stable
  - '4.0.0'
  - '0.12'
sudo: false
deploy:
  provider: npm
  email: pattyn.kurt@gmail.com
  api_key:
    secure: gsqKVo83+jNucsnV4OWVRfi1Pty1ojLvg4TEVpE97uESTXXxcwPpLybXV/ROp3RU3K7NR/5MCai0EWTIH/4bwC4L5U/GgQdLoolfUhF+5JSrSEKZnvSQNVFieRwHHN34hyD6i19jAfbeekgAU2ZavQZ/IamnFMfaqZcxvWO6Dnxn5wuTu51DipWStLDKuhnKx9tTLAh4JvnqSfUipYo5yrHm5mb1lV5jC3h8Z2ymKL62CnT8mFtb7N7juTSFWrM5egPbSujKsoEbfXTOIdi6OuAWF9qMKx43oL+1Wq5olPe6nCKmou0jABjlfqf+wfilC3DMYsn/mQL6J9PZ9mQ/eTb+V5zonkUM7Shhc9DrD8ploXf3pwrVk3Y61gs5zpSqePclp5lOxcI7oSeNcsWebOzkXg2aLxkHt2pHp37MHdQ7Zxkl4ziILZUcRNDiZJUDnk1Wcu9Eq0ZZA2KCPBDkxswcmbN3WDMadEzHYBejlRtUNm0vq1LqY6pUOXHAo4lbqEvxQ/hIlhUacmPWP8K0Dtx0lWBdN3y+E2xMe1oqBFgub0tXAESBfKpNzg+v2Phs4Zyb9P5h+B1wQxle40SohqumePnE/xAUIDqAi7rQg+OImvInO3mDB1jwyl4KOzE7feqEUfSu2d6TaaOY6Tun7j6LqhZWOPn787OE3gSC3Mk=
  on:
    tags: true
    repo: KurtPattyn/karl
    branch: master
addons:
  code_climate:
    repo_token: a5b7451aa9dd5b54e35a08f783e89ccca7a32b9d3ef953f61686bbcea997ed89
before_script:
  - npm run check-style
  - npm run code-analysis
script:
  - npm run test-ci
  - npm run check-coverage
after_success:
  - npm install coveralls && cat ./coverage/lcov.info | coveralls
  - npm install codeclimate-test-reporter && codeclimate-test-reporter < ./coverage/lcov.info
